name: material_floating_search_bar
description: A Flutter implementation of an expandable and animated floating search bar, also known as persistent search.
version: 0.2.6
repository: https://github.com/bnxm/material_floating_search_bar

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: